name: Auto-merge

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  build-version:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: git
      run: |
        git --version
        git config --local user.email "githubbot@ian.mn"
        git config --local user.name "Ian Mckay [bot]"
        git remote add aws https://github.com/aws/aws-sdk-js.git || true
        git pull aws master || true
        git checkout --ours -- README.md
        git add README.md
        git add .
        git commit -m "Auto-merge" -a
        remote_repo="https://iann0036-bot:${BOT_GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git push "${remote_repo}" HEAD:main
